# Project 5 -- Lukas Anell

In [1]:
# /anvil/projects/tdm/data/flights/subset/1987.csv (used in an example)
# /anvil/projects/tdm/data/lahman/data/AllstarFull.csv
# /anvil/projects/tdm/data/flights/subset/2005.csv

## Question 1

In [2]:
import pandas as pd
import polars as pl
import time

In [3]:
start = time.time()
pandas_df = pd.read_csv('/anvil/projects/tdm/data/flights/subset/1987.csv', header=None , dtype='unicode')
end = time.time()
print(f"Pandas read_csv took {end - start} seconds")

Pandas read_csv took 3.1500377655029297 seconds

In [4]:
pandas_df.head()

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
1,1987,10,14,3,741,730,912,849,PS,1451,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,1987,10,15,4,729,730,903,849,PS,1451,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,1987,10,17,6,741,730,918,849,PS,1451,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,1987,10,18,7,729,730,847,849,PS,1451,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [5]:
start = time.time()
polars_df = pl.read_csv('/anvil/projects/tdm/data/flights/subset/1987.csv', has_header=False)
end = time.time()
print(f"Polars read_csv took {end - start} seconds")

Polars read_csv took 0.7260646820068359 seconds

In [6]:
polars_df.head()

shape: (5, 29)
┌──────────┬──────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ column_1 ┆ column_2 ┆ column_3   ┆ column_4  ┆ … ┆ column_26 ┆ column_27 ┆ column_28 ┆ column_29 │
│ ---      ┆ ---      ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str      ┆ str      ┆ str        ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ str       │
╞══════════╪══════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Year     ┆ Month    ┆ DayofMonth ┆ DayOfWeek ┆ … ┆ WeatherDe ┆ NASDelay  ┆ SecurityD ┆ LateAircr │
│          ┆          ┆            ┆           ┆   ┆ lay       ┆           ┆ elay      ┆ aftDelay  │
│ 1987     ┆ 10       ┆ 14         ┆ 3         ┆ … ┆ NA        ┆ NA        ┆ NA        ┆ NA        │
│ 1987     ┆ 10       ┆ 15         ┆ 4         ┆ … ┆ NA        ┆ NA        ┆ NA        ┆ NA        │
│ 1987     ┆ 10       ┆ 17         ┆ 6         ┆ … ┆ NA        ┆ NA        ┆ NA        ┆ NA        │
│ 1987     ┆ 10       ┆ 18         ┆ 7         ┆ … ┆ NA        ┆ NA        ┆ NA        ┆ NA        │
└──────────┴──────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [7]:
start = time.time()
pandas_df = pd.read_csv('/anvil/projects/tdm/data/lahman/data/AllstarFull.csv', header=None)
pandas_df.columns = ['playerID', 'yearID', 'gameNum', 'gameID', 'teamID', 'lgID', 'GP', 'startingPos']
end = time.time()
print(f"Pandas read_csv took {end - start} seconds")

Pandas read_csv took 0.009543657302856445 seconds

In [8]:
pandas_df.head()

    playerID  yearID  gameNum        gameID teamID lgID  GP  startingPos
0  kalinal01    1957        0  NLS195707090    DET   AL   1          9.0
1  demaejo01    1957        0  NLS195707090    KC1   AL   0          NaN
2   grimbo01    1957        0  NLS195707090    NYA   AL   1          NaN
3  howarel01    1957        0  NLS195707090    NYA   AL   0          NaN
4   loesbi01    1957        0  NLS195707090    BAL   AL   1          NaN

In [9]:
start = time.time()
polars_df = pl.read_csv('/anvil/projects/tdm/data/lahman/data/AllstarFull.csv', has_header=False)
polars_df.columns = ['playerID', 'yearID', 'gameNum', 'gameID', 'teamID', 'lgID', 'GP', 'startingPos']
end = time.time()
print(f"Polars read_csv took {end - start} seconds")

Polars read_csv took 0.015880584716796875 seconds

In [10]:
polars_df.head()

shape: (5, 8)
┌───────────┬────────┬─────────┬──────────────┬────────┬──────┬─────┬─────────────┐
│ playerID  ┆ yearID ┆ gameNum ┆ gameID       ┆ teamID ┆ lgID ┆ GP  ┆ startingPos │
│ ---       ┆ ---    ┆ ---     ┆ ---          ┆ ---    ┆ ---  ┆ --- ┆ ---         │
│ str       ┆ i64    ┆ i64     ┆ str          ┆ str    ┆ str  ┆ i64 ┆ i64         │
╞═══════════╪════════╪═════════╪══════════════╪════════╪══════╪═════╪═════════════╡
│ kalinal01 ┆ 1957   ┆ 0       ┆ NLS195707090 ┆ DET    ┆ AL   ┆ 1   ┆ 9           │
│ demaejo01 ┆ 1957   ┆ 0       ┆ NLS195707090 ┆ KC1    ┆ AL   ┆ 0   ┆ null        │
│ grimbo01  ┆ 1957   ┆ 0       ┆ NLS195707090 ┆ NYA    ┆ AL   ┆ 1   ┆ null        │
│ howarel01 ┆ 1957   ┆ 0       ┆ NLS195707090 ┆ NYA    ┆ AL   ┆ 0   ┆ null        │
│ loesbi01  ┆ 1957   ┆ 0       ┆ NLS195707090 ┆ BAL    ┆ AL   ┆ 1   ┆ null        │
└───────────┴────────┴─────────┴──────────────┴────────┴──────┴─────┴─────────────┘

When running the first `pd.read_csv()` it was giving me a warning about specifying dtypes or a low memory mode, so I found a stack overflow [thread](https://stackoverflow.com/questions/24251219/pandas-read-csv-low-memory-and-dtype-options) online that fixed it.

1.1: Pandas took 2.8264 seconds while polars took 0.8363 seconds.

1.2: Pandas took 0.0090 seconds while polars took 0.0135 seconds.

1.3: Pandas seems to be faster for smaller datasets, but it's runtime grows faster for larger datasets. Polars seems to be slower for those same smaller datasets, but the runtime for larger datasets doesn't grow as fast.

## Question 2

In [11]:
pandas_df[['playerID', 'teamID']]

       playerID teamID
0     kalinal01    DET
1     demaejo01    KC1
2      grimbo01    NYA
3     howarel01    NYA
4      loesbi01    BAL
...         ...    ...
5668  mantijo01    ARI
5669  mikolmi01    SLN
5670  musgrjo01    SDN
5671  rodonca01    SFN
5672  willide03    MIL

[5673 rows x 2 columns]

In [12]:
polars_df.select(pl.col("playerID"), pl.col("teamID"))

shape: (5_673, 2)
┌───────────┬────────┐
│ playerID  ┆ teamID │
│ ---       ┆ ---    │
│ str       ┆ str    │
╞═══════════╪════════╡
│ kalinal01 ┆ DET    │
│ demaejo01 ┆ KC1    │
│ grimbo01  ┆ NYA    │
│ howarel01 ┆ NYA    │
│ loesbi01  ┆ BAL    │
│ …         ┆ …      │
│ mantijo01 ┆ ARI    │
│ mikolmi01 ┆ SLN    │
│ musgrjo01 ┆ SDN    │
│ rodonca01 ┆ SFN    │
│ willide03 ┆ MIL    │
└───────────┴────────┘

In [13]:
philly_players_pandas = pandas_df[pandas_df['teamID'] == "PHI"]
philly_players_pandas.head()

      playerID  yearID  gameNum        gameID teamID lgID  GP  startingPos
17   simmocu01    1957        0  NLS195707090    PHI   NL   1          1.0
38   sanfoja02    1957        0  NLS195707090    PHI   NL   1          NaN
77   ashburi01    1958        0  ALS195807080    PHI   NL   0          NaN
80   farretu01    1958        0  ALS195807080    PHI   NL   1          NaN
176  conlege01    1959        1  NLS195907070    PHI   NL   0          NaN

In [14]:
philly_players_polars = polars_df.filter(pl.col("teamID") == "PHI")
philly_players_polars.head()

shape: (5, 8)
┌───────────┬────────┬─────────┬──────────────┬────────┬──────┬─────┬─────────────┐
│ playerID  ┆ yearID ┆ gameNum ┆ gameID       ┆ teamID ┆ lgID ┆ GP  ┆ startingPos │
│ ---       ┆ ---    ┆ ---     ┆ ---          ┆ ---    ┆ ---  ┆ --- ┆ ---         │
│ str       ┆ i64    ┆ i64     ┆ str          ┆ str    ┆ str  ┆ i64 ┆ i64         │
╞═══════════╪════════╪═════════╪══════════════╪════════╪══════╪═════╪═════════════╡
│ simmocu01 ┆ 1957   ┆ 0       ┆ NLS195707090 ┆ PHI    ┆ NL   ┆ 1   ┆ 1           │
│ sanfoja02 ┆ 1957   ┆ 0       ┆ NLS195707090 ┆ PHI    ┆ NL   ┆ 1   ┆ null        │
│ ashburi01 ┆ 1958   ┆ 0       ┆ ALS195807080 ┆ PHI    ┆ NL   ┆ 0   ┆ null        │
│ farretu01 ┆ 1958   ┆ 0       ┆ ALS195807080 ┆ PHI    ┆ NL   ┆ 1   ┆ null        │
│ conlege01 ┆ 1959   ┆ 1       ┆ NLS195907070 ┆ PHI    ┆ NL   ┆ 0   ┆ null        │
└───────────┴────────┴─────────┴──────────────┴────────┴──────┴─────┴─────────────┘

In [15]:
philly_players_2023_pd = philly_players_pandas.sort_values(by="yearID", ascending=False)
philly_players_2023_pd.head()

       playerID  yearID  gameNum        gameID teamID lgID  GP  startingPos
5536  casteni01    2023        0  ALS202307110    PHI   NL   1          NaN
5548  kimbrcr01    2023        0  ALS202307110    PHI   NL   1          NaN
5654  schwaky01    2022        0  NLS202207190    PHI   NL   1          NaN
5512  schwaky01    2022        0  NLS202207190    PHI   NL   1          NaN
5655  harpebr03    2022        0  NLS202207190    PHI   NL   0          NaN

In [16]:
philly_players_2023_pl = philly_players_polars.sort("yearID", descending=True)
philly_players_2023_pl.head()

shape: (5, 8)
┌───────────┬────────┬─────────┬──────────────┬────────┬──────┬─────┬─────────────┐
│ playerID  ┆ yearID ┆ gameNum ┆ gameID       ┆ teamID ┆ lgID ┆ GP  ┆ startingPos │
│ ---       ┆ ---    ┆ ---     ┆ ---          ┆ ---    ┆ ---  ┆ --- ┆ ---         │
│ str       ┆ i64    ┆ i64     ┆ str          ┆ str    ┆ str  ┆ i64 ┆ i64         │
╞═══════════╪════════╪═════════╪══════════════╪════════╪══════╪═════╪═════════════╡
│ casteni01 ┆ 2023   ┆ 0       ┆ ALS202307110 ┆ PHI    ┆ NL   ┆ 1   ┆ null        │
│ kimbrcr01 ┆ 2023   ┆ 0       ┆ ALS202307110 ┆ PHI    ┆ NL   ┆ 1   ┆ null        │
│ schwaky01 ┆ 2022   ┆ 0       ┆ NLS202207190 ┆ PHI    ┆ NL   ┆ 1   ┆ null        │
│ schwaky01 ┆ 2022   ┆ 0       ┆ NLS202207190 ┆ PHI    ┆ NL   ┆ 1   ┆ null        │
│ harpebr03 ┆ 2022   ┆ 0       ┆ NLS202207190 ┆ PHI    ┆ NL   ┆ 0   ┆ null        │
└───────────┴────────┴─────────┴──────────────┴────────┴──────┴─────┴─────────────┘

I like how similar most of polars' functions are to pandas, it makes it easier to learn for me.

2.1: See above.

2.2: See above.

2.3: See above.

## Question 3

In [23]:
myDF = pl.read_csv("/anvil/projects/tdm/data/flights/subset/2005.csv")

In [24]:
myDF.head()

shape: (5, 29)
┌──────┬───────┬────────────┬───────────┬───┬──────────────┬──────────┬──────────────┬─────────────┐
│ Year ┆ Month ┆ DayofMonth ┆ DayOfWeek ┆ … ┆ WeatherDelay ┆ NASDelay ┆ SecurityDela ┆ LateAircraf │
│ ---  ┆ ---   ┆ ---        ┆ ---       ┆   ┆ ---          ┆ ---      ┆ y            ┆ tDelay      │
│ i64  ┆ i64   ┆ i64        ┆ i64       ┆   ┆ i64          ┆ i64      ┆ ---          ┆ ---         │
│      ┆       ┆            ┆           ┆   ┆              ┆          ┆ i64          ┆ i64         │
╞══════╪═══════╪════════════╪═══════════╪═══╪══════════════╪══════════╪══════════════╪═════════════╡
│ 2005 ┆ 1     ┆ 28         ┆ 5         ┆ … ┆ 0            ┆ 0        ┆ 0            ┆ 0           │
│ 2005 ┆ 1     ┆ 29         ┆ 6         ┆ … ┆ 0            ┆ 0        ┆ 0            ┆ 0           │
│ 2005 ┆ 1     ┆ 30         ┆ 7         ┆ … ┆ 0            ┆ 0        ┆ 0            ┆ 0           │
│ 2005 ┆ 1     ┆ 31         ┆ 1         ┆ … ┆ 0            ┆ 0        ┆ 0            ┆ 0           │
│ 2005 ┆ 1     ┆ 2          ┆ 7         ┆ … ┆ 0            ┆ 0        ┆ 0            ┆ 0           │
└──────┴───────┴────────────┴───────────┴───┴──────────────┴──────────┴──────────────┴─────────────┘

In [27]:
indy_flights = myDF.filter(pl.col("Origin") == "IND")
indy_flights.select(pl.col("^CRS.*$")).head()

shape: (5, 3)
┌────────────┬────────────┬────────────────┐
│ CRSDepTime ┆ CRSArrTime ┆ CRSElapsedTime │
│ ---        ┆ ---        ┆ ---            │
│ i64        ┆ i64        ┆ i64            │
╞════════════╪════════════╪════════════════╡
│ 1602       ┆ 1614       ┆ 72             │
│ 1602       ┆ 1614       ┆ 72             │
│ 1602       ┆ 1614       ┆ 72             │
│ 1602       ┆ 1614       ┆ 72             │
│ 1602       ┆ 1614       ┆ 72             │
└────────────┴────────────┴────────────────┘

Reading the csv with 2 cores didn't work, it kept crashing the kernel, so I switched to 4 cores.

3.1: It seems like almost everything has the same or similar names, between the two. Selecting columns is different, which probably has something to do with the data structures used which would require function calls for polars but not for pandas.

3.2: See above.

3.3: See above.

## Question 4

In [36]:
indy_flights.select(pl.col("^.*Delay.*$")).head()

shape: (5, 7)
┌──────────┬──────────┬──────────────┬──────────────┬──────────┬───────────────┬───────────────────┐
│ ArrDelay ┆ DepDelay ┆ CarrierDelay ┆ WeatherDelay ┆ NASDelay ┆ SecurityDelay ┆ LateAircraftDelay │
│ ---      ┆ ---      ┆ ---          ┆ ---          ┆ ---      ┆ ---           ┆ ---               │
│ str      ┆ str      ┆ i64          ┆ i64          ┆ i64      ┆ i64           ┆ i64               │
╞══════════╪══════════╪══════════════╪══════════════╪══════════╪═══════════════╪═══════════════════╡
│ 37       ┆ 39       ┆ 8            ┆ 0            ┆ 0        ┆ 0             ┆ 29                │
│ 10       ┆ 25       ┆ 0            ┆ 0            ┆ 0        ┆ 0             ┆ 0                 │
│ 83       ┆ 84       ┆ 0            ┆ 0            ┆ 83       ┆ 0             ┆ 0                 │
│ -11      ┆ 5        ┆ 0            ┆ 0            ┆ 0        ┆ 0             ┆ 0                 │
│ 194      ┆ 192      ┆ 0            ┆ 0            ┆ 130      ┆ 0             ┆ 64                │
└──────────┴──────────┴──────────────┴──────────────┴──────────┴───────────────┴───────────────────┘

In [37]:
indy_flights.select(pl.col("^(Arr|Dep).*$")).head()

shape: (5, 4)
┌─────────┬─────────┬──────────┬──────────┐
│ DepTime ┆ ArrTime ┆ ArrDelay ┆ DepDelay │
│ ---     ┆ ---     ┆ ---      ┆ ---      │
│ str     ┆ str     ┆ str      ┆ str      │
╞═════════╪═════════╪══════════╪══════════╡
│ 1641    ┆ 1651    ┆ 37       ┆ 39       │
│ 1627    ┆ 1624    ┆ 10       ┆ 25       │
│ 1726    ┆ 1737    ┆ 83       ┆ 84       │
│ 1607    ┆ 1603    ┆ -11      ┆ 5        │
│ 1914    ┆ 1928    ┆ 194      ┆ 192      │
└─────────┴─────────┴──────────┴──────────┘

In [39]:
indy_flights.select(pl.col(r"^(Arr|Dep).*Delay$")).head()

shape: (5, 2)
┌──────────┬──────────┐
│ ArrDelay ┆ DepDelay │
│ ---      ┆ ---      │
│ str      ┆ str      │
╞══════════╪══════════╡
│ 37       ┆ 39       │
│ 10       ┆ 25       │
│ 83       ┆ 84       │
│ -11      ┆ 5        │
│ 194      ┆ 192      │
└──────────┴──────────┘

Knowing regex is, unsurprisingly, very useful for this. I'd assume it's often useful when working with data.

4.1: 7 of the columns have the word Delay in them.

4.2: See above.

4.3: See above.

## Question 5

In [40]:
myDF = myDF.with_columns(
    pl.col("ArrTime").cast(pl.Int64, strict=False)
)

In [49]:
myDF.with_columns(((pl.col("ArrTime") - pl.col("CRSArrTime")).abs().alias("AbsDiffArrTime"))).head()

shape: (5, 30)
┌──────┬───────┬────────────┬───────────┬───┬──────────┬──────────────┬──────────────┬─────────────┐
│ Year ┆ Month ┆ DayofMonth ┆ DayOfWeek ┆ … ┆ NASDelay ┆ SecurityDela ┆ LateAircraft ┆ AbsDiffArrT │
│ ---  ┆ ---   ┆ ---        ┆ ---       ┆   ┆ ---      ┆ y            ┆ Delay        ┆ ime         │
│ i64  ┆ i64   ┆ i64        ┆ i64       ┆   ┆ i64      ┆ ---          ┆ ---          ┆ ---         │
│      ┆       ┆            ┆           ┆   ┆          ┆ i64          ┆ i64          ┆ i64         │
╞══════╪═══════╪════════════╪═══════════╪═══╪══════════╪══════════════╪══════════════╪═════════════╡
│ 2005 ┆ 1     ┆ 28         ┆ 5         ┆ … ┆ 0        ┆ 0            ┆ 0            ┆ 18          │
│ 2005 ┆ 1     ┆ 29         ┆ 6         ┆ … ┆ 0        ┆ 0            ┆ 0            ┆ 23          │
│ 2005 ┆ 1     ┆ 30         ┆ 7         ┆ … ┆ 0        ┆ 0            ┆ 0            ┆ 64          │
│ 2005 ┆ 1     ┆ 31         ┆ 1         ┆ … ┆ 0        ┆ 0            ┆ 0            ┆ 33          │
│ 2005 ┆ 1     ┆ 2          ┆ 7         ┆ … ┆ 0        ┆ 0            ┆ 0            ┆ 3           │
└──────┴───────┴────────────┴───────────┴───┴──────────┴──────────────┴──────────────┴─────────────┘

5.1: See above.

5.2: See above.

5.3: See above.

## Pledge

By submitting this work I hereby pledge that this is my own, personal work. I've acknowledged in the designated place at the top of this file all sources that I used to complete said work, including but not limited to: online resources, books, and electronic communications. I've noted all collaboration with fellow students and/or TA's. I did not copy or plagiarize another's work.

> As a Boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together – We are Purdue.

https://www.purdue.edu/odos/osrr/honor-pledge/